# Change these first
owner: cotezos # Your GitHub organization or username, where this repository lives
repo: umami-api-endpoints # The name of this repository

sites:
  - name: Umami API mainnet 
    url: https://mainnet.umamiwallet.com/monitor/blocks
  - name: Umami API ghostnet 
    url: https://ghostnet.umamiwallet.com/monitor/blocks
    
#   - name: Umami API kathmandunet 
#     url: https://kathmandunet.umamiwallet.com/monitor/blocks
#  - name: Umami API limanet 
#    url: https://limanet.umamiwallet.com/monitor/blocks
#  - name: Umami API mumbainet 
#    url: https://mumbainet.umamiwallet.com/monitor/blocks

  - name: QA Umami API mainnet (QA: for testing, do not use)
    url: https://mainnet-qa.umamiwallet.com/monitor/blocks
  - name: QA Umami API ghostnet (QA: for testing, do not use)
    url: https://ghostnet-qa.umamiwallet.com/monitor/blocks
    
#     - name: DEV Umami API mainnet (DEV: no guaranty, do not use)
#     url: https://mainnet-dev.umamiwallet.com/monitor/blocks
#   - name: DEV Umami API ghostnet (DEV: no guaranty, do not use)
#     url: https://ghostnet-dev.umamiwallet.com/monitor/blocks
      


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /umami-api-endpoints
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for public Umami Tezos Wallet API endpoints
  introTitle: "**Umami Tezos Wallet API endpoints Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
